- name: Demo on variables 
  hosts: all
  vars:
    URL: play.google.com     #global/play level variable
  tasks:  
    - name: Print the url
      ansible.builtin.debug:
        msg: The value of URL is {{URL}}

    - name: Print the url
      ansible.builtin.debug:
        msg: The value of URL is {{URL}}
      vars:
        URL: task.google.com     #task level variable

    - name: Print the CLI url
      ansible.builtin.debug:
        msg: The value of CLI URL is {{CLI_URL}}  #no variable is declared and it will throw an exception

        #we can supply variables from command line also referred as run time variable.

        ### CLI variables > Local vars > Global vars
          