- name: Demo on facts
  hosts: all
  tasks:
    - name: Print fact
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Print mac address
      ansible.builtin.debug:
        msg: "{{ ansible_default_ipv4.mac_address }}"

        ## if a variable is at start of line, then include it in double quotes.