- name: Demo on variables 
  hosts: all
  tasks:  
    - name: Run shell command
      shell: uptime
      register: OUT

    - name: printing the output of uptime
      debug:
        msg: "{{OUT}}" 


      ## Register is helpful in taking the output and using it wherever required.
      ## use OUT.stdout in case only expected output is required