- name: Demo on variables 
  hosts: all
  tasks:  
    - name: Run shell command
      shell: uptime
      register: OUT

     -name: printing the output
      debug:
        msg: "{{OUT}}" 


      ## Register is helpful in taking the output and using it wherever required.