- name: demo on tags
  hosts: all
  tasks:
    - name: running webserver installation
      debug:
        msg: webserver installation
      tags: web

    - name: starting webserver
      debug:
        msg: webserver start in progress
      tags: web

    - name: starting appserver
      debug:
        msg: appserver start in progress
      tags: app