- name: Play1 
  hosts: all  
  tasks:  
    - name: Print Hello from Play1 
      ansible.builtin.debug:
        msg: Hello from task1 of play1 

- name: play4
  hosts: all
  tasks:
    - name: Print Hello from Play2
      ansible.builtin.debug:
        msg: Hello from task1 of play1  