- name: Configure the yum repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name:
      - nodejs
      - gcc-c++
    state: present

- name: create user account {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download




