- name: Configure the yum repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name:
      - nodejs
      - gcc-c++
    state: present

# - name: Creating user {{APPUSER}}
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: create-user

# - name: Download and extracting {{COMPONENT}}
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download

- name: Cleanup of {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: cleanup

- name: Install packages based on package.json
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring and starting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

- name: set the hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: system-hostname         