- name: copy systemd.service file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: starting the {{COMPONENT}} service
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes 